set shell := ["bash", "-c"]

MCU := "{{env.MCU or 'ch32v203'}}"
BUILD_DIR := "build"

build:
    mkdir -p {{BUILD_DIR}}/$MCU
    $CC $CFLAGS \
        firmware/$MCU/main.c \
        $SDK_SRC/*.c \
        -T firmware/$MCU/linker.ld \
        -o {{BUILD_DIR}}/$MCU/firmware.elf

flash:
    wlink flash {{BUILD_DIR}}/$MCU/firmware.elf

clean:
    rm -rf {{BUILD_DIR}}
